<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.melluh</groupId>
    <artifactId>ServerTours</artifactId>
    <version>${env.project.version}</version>
    <packaging>pom</packaging>

    <properties>
        <env.java.version>17</env.java.version>
        <env.project.version>2.1.7</env.project.version>
    </properties>

    <name>ServerTours</name>

    <modules>
        <module>nms</module>
        <module>base</module>
        <module>v1_21_4</module>
        <module>v1_21_5</module>
    </modules>

    <repositories>
        <repository>
            <id>huawei-maven</id>
            <url>https://repo.huaweicloud.com/repository/maven</url>
        </repository>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public</url>
        </repository>
        <repository>
            <id>codemc-releases</id>
            <url>https://repo.codemc.io/repository/maven-releases</url>
        </repository>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>SilverMoonvalley-Maven-Repo-releases</id>
            <name>银月谷开发组私有maven仓库</name>
            <url>http://103.205.253.165:30001/releases</url>
        </repository>
    </repositories>
</project>