name: ServerTours
version: 2.1.7
main: com.melluh.servertours.ServerTours
description: Easily create beautiful tours around your server.
author: Melluh
depend:
 - ProtocolLib
commands:
  tour:
    description: "Used to create, manage and play tour routes"
permissions:
  servertours.commands.play:
    default: "true"
api-version: 1.17
softdepend:
 - PlaceholderAPI
 - VentureChat
 - floodgate