name: ServerTours
version: 3.0.0
main: com.melluh.servertours.ServerTours
description: Easily create beautiful tours around your server.
author: Melluh
depend:
 - ProtocolLib
commands:
  tour:
    description: "Used to create, manage and play tour routes"
permissions:
  servertours.commands.play:
    default: "true"
  servertours.commands.record:
    default: "op"
  servertours.commands.record.manage:
    default: "op"
api-version: 1.17
softdepend:
 - PlaceholderAPI
 - VentureChat
 - floodgate
